productInfoExtraction:
  description: >
    Extracting brand name and the product name of the clothing item from the provided URL {user_URL}. 
    The extracted data should be structured and ready for further analysis.
  expected_output: >
    The Product name and the brand name.

sustainabilityAnalysis:
  description: >
    Based on the brand name, do a comprehensive sustainability credentials analysis of 
    this clothing brand.
  expected_output: >
    A fully fledge sustainability performance report with the Certification check, Brand reputation analysis, environmental impact, 
    life cycle assessment, sustainability score etc with a conclusion and references to the resources.

sustainableProductResearch:
  description: >
    Based on the product name and the brand name, find sustainable clothing alternatives to 
    this clothing product. Make sure to prioritize searching for alternatives with similar styles and 
    functionalities to the original product. Prioritize options with relevant sustainability certifications, positive user reviews regarding ethical practices, 
    or eco-friendly materials.
  expected_output: >
    A manageble list of curated alternative products with product details such as Brand Name, product name, 
    sustainability details (certifications etc) and references to the online resources of the products.

finalProductReport:
  description: >
    Compile a comprehensive and user-friendly report for the product that outlines all the previous findings. 
    The report should include the original product name and brand, sustainability analysis and the alternative sustainable product list.
  expected_output: >
    A detailed report that includes the original product name and brand, brand sustainability analysis, and the curated list of alternative sustainable products. 
    The report should be formatted as markdown and highlight the sustainability strengths and weaknesses of the original brand and showcase the key eco-conscious aspects of the alternative options.